name: Check need info

on:
  schedule:
    - cron: "0 0 */14 * *"

jobs:
  check-need-info:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v1.11
        with:
          actions: "close-issues"
          token: ${{ secrets.RYAN_TOKEN }}
          labels: "ğŸ˜„ to do"
          issue-assignee: "Ryanjiena"
          inactive-day: 14
          body: |
            "ç”±äºè¯¥ issue è¢«æ ‡è®°ä¸º \`to do\`ï¼Œå´ 14 å¤©æœªæ”¶åˆ°å›åº”ã€‚ç°å…³é—­ issueï¼Œè‹¥æœ‰ä»»ä½•é—®é¢˜ï¼Œå¯è¯„è®ºå›å¤ã€‚"
            "Since the issue was labeled with `to do`, but no response in 14 days. This issue will be closed. If you have any questions, you can comment and reply."
            
      - name: Remove labels
          uses: actions-cool/issues-helper@v1.11
          with:
            actions: 'remove-labels'
            token: ${{ secrets.RYAN_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            labels: 'ğŸ˜„ to do,in-progress,priority-2'

